{
  "compatibilityLevel": 1600,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Customer\",\"Product\",\"Region\",\"Sales_Historical\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US"
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "971e9d64-23eb-4193-844d-22d31df8b0cd",
        "fromColumn": "JoinDate",
        "fromTable": "Customer",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_849da51f-7125-48a0-8f0c-9406c1147c1a"
      },
      {
        "name": "5f17090d-ec78-4418-b285-e78cb44379fd",
        "fromColumn": "Date",
        "fromTable": "Sales_Historical",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_24f2ef6a-195b-4145-a89e-e9fdb171a737"
      },
      {
        "name": "AutoDetected_6422c703-0b64-4f09-b938-74168550b138",
        "fromColumn": "CustomerID",
        "fromTable": "Sales_Historical",
        "toColumn": "CustomerID",
        "toTable": "Customer"
      },
      {
        "name": "AutoDetected_b1d530c7-a735-4b95-b465-62da9202935f",
        "fromColumn": "ProductID",
        "fromTable": "Sales_Historical",
        "toColumn": "ProductID",
        "toTable": "Product"
      },
      {
        "name": "AutoDetected_1345545c-a3c6-4284-8c6c-5ecf85c36a7c",
        "fromColumn": "RegionID",
        "fromTable": "Sales_Historical",
        "toColumn": "RegionID",
        "toTable": "Region"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Customer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92caa587-853a-484a-9fba-7ccc8e64a9e1",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c5d25d5-06d5-4437-839a-8771be2f757a",
            "sourceColumn": "CustomerName",
            "summarizeBy": "none"
          },
          {
            "name": "Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39efa841-ac4c-4b86-9ccb-d45fb7e5a358",
            "sourceColumn": "Segment",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0831c4cd-7721-4d5b-9ba1-0d872353e35c",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e533aa1e-a2d9-4a27-9702-efc22494c4ff",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4240c3b8-b7e6-4190-a56d-edaff18dfd88",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "JoinDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ae53a56e-67ad-41c0-8791-e26ee6a4cb2b",
            "sourceColumn": "JoinDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_849da51f-7125-48a0-8f0c-9406c1147c1a"
                },
                "isDefault": true,
                "relationship": "971e9d64-23eb-4193-844d-22d31df8b0cd"
              }
            ]
          }
        ],
        "lineageTag": "feaa5b57-94da-4be4-a499-c3aac520fc35",
        "partitions": [
          {
            "name": "Customer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\P0605227\\OneDrive - Saint-Gobain\\Desktop\\Power BI Training\\Customer.xlsx\"), null, true),",
                "    Customer_Sheet = Source{[Item=\"Customer\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Customer_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CustomerID\", type text}, {\"CustomerName\", type text}, {\"Segment\", type text}, {\"Country\", type text}, {\"City\", type text}, {\"Region\", type text}, {\"JoinDate\", type date}, {\"Column8\", type any}, {\"Column9\", type any}, {\"Column10\", type any}, {\"Column11\", type any}, {\"Column12\", type any}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_7d7e40c7-3649-46da-8447-a7ae950e81b6",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3de50520-fe9e-4940-92fe-8931841eedbc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "50902bfc-d10a-4a54-8537-4a23b19d5ce3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2cc2304f-5817-4aa5-9697-631b7ae5765c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "2ac38dde-6242-4a5a-82d5-a0ea60dd8790",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a9d6a108-bbed-4391-985f-2255d92a21d3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "d5093086-d157-44e9-b0c6-e69794527388",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "20d81c78-ddba-4c60-b74d-ba3d59745518",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "2939f789-ad9b-4e6e-be2b-fdfd6a58ffea",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "29297aa7-e5d4-4ae4-b882-5cfba1531464",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "98cfcfd5-6a10-496c-aeaf-cf5685519d57",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "aa20676c-0003-488e-88f6-4b136bb5fab4",
                "ordinal": 3
              }
            ],
            "lineageTag": "e16022b5-b62a-430f-84c8-f81fc1eb5087"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "3e0f3239-234d-4860-a7a3-a7dc179f23c6",
        "partitions": [
          {
            "name": "DateTableTemplate_7d7e40c7-3649-46da-8447-a7ae950e81b6",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_849da51f-7125-48a0-8f0c-9406c1147c1a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e06a3693-f758-4fb5-9204-c6924db1d929",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "34ed32fd-56dc-4e96-859a-92f679a89829",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c2324f0a-7552-4cd6-9401-49af817e7c2c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "05f97315-0b8d-471f-8750-5ca1a3eaeab6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6ccbdd74-996b-45ec-8f96-4d2929422e39",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "bc583b78-d84d-4aac-8f58-e870bf261c0c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ea3b4350-9707-4259-ba2d-5e0f8f26b789",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "507efcf3-d704-46eb-b7e3-6a4dbd64d74f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8d153b8c-36d5-464d-9934-2b96e3b4c682",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "33944b5b-545e-473a-baa0-7abc2e2ca13d",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2021ea9c-117a-414c-884e-581be863f3ef",
                "ordinal": 3
              }
            ],
            "lineageTag": "a0350bfc-937a-497a-a95f-7cfd921731f4"
          }
        ],
        "isHidden": true,
        "lineageTag": "81a4d6a7-c3c7-49df-87ed-88fd631f7364",
        "partitions": [
          {
            "name": "LocalDateTable_849da51f-7125-48a0-8f0c-9406c1147c1a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Customer'[JoinDate])), 1, 1), Date(Year(MAX('Customer'[JoinDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Product",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3eaec366-f1e9-48c7-b001-4b7a89e0dccb",
            "sourceColumn": "ProductID",
            "summarizeBy": "none"
          },
          {
            "name": "ProductName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2d34d32-8caf-4d5b-ab01-cd768eecfcce",
            "sourceColumn": "ProductName",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ed5ef5b-1642-482b-a4f1-b9ada022aef5",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "SubCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a18c8f65-6bbc-402f-a992-4911b715f096",
            "sourceColumn": "SubCategory",
            "summarizeBy": "none"
          },
          {
            "name": "UnitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a3ac0688-8376-4747-9054-4a5dd16bca06",
            "sourceColumn": "UnitPrice",
            "summarizeBy": "none"
          },
          {
            "name": "UnitCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bc4df1e9-803f-4c93-8be7-c40be54884fa",
            "sourceColumn": "UnitCost",
            "summarizeBy": "none"
          },
          {
            "name": "Margin %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c50e14b-fdeb-4614-8dfd-219763da5885",
            "sourceColumn": "Margin %",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f535a4aa-ae89-4be5-93b3-d774659e4092",
        "measures": [
          {
            "name": "AverageUnitPrice",
            "expression": "AVERAGE('Product'[UnitPrice])",
            "lineageTag": "60725a9e-13b7-45be-8808-cb2cc12f09d1"
          },
          {
            "name": "AverageUnitPriceFromProduct",
            "expression": "AVERAGE(Product[UnitPrice])",
            "lineageTag": "4bd2afb6-e814-4bf4-b7c9-7cc53f50c874"
          }
        ],
        "partitions": [
          {
            "name": "Product",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\P0605227\\OneDrive - Saint-Gobain\\Desktop\\Power BI Training\\Product.xlsx\"), null, true),",
                "    Product_Sheet = Source{[Item=\"Product\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Product_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"SAINT-GOBAIN  |  Product Master Data\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type any}, {\"Column6\", type any}, {\"Column7\", type text}}),",
                "    #\"Promoted Headers1\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers1\",{{\"ProductID\", type text}, {\"ProductName\", type text}, {\"Category\", type text}, {\"SubCategory\", type text}, {\"UnitPrice\", Int64.Type}, {\"UnitCost\", Int64.Type}, {\"Margin %\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Region",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "RegionID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bca9638c-525d-4559-a598-88a8958a4318",
            "sourceColumn": "RegionID",
            "summarizeBy": "none"
          },
          {
            "name": "RegionName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ffde35f-0ace-4534-9130-01c9326600a7",
            "sourceColumn": "RegionName",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11395c11-ef99-42da-821e-fb169c067c76",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Zone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07b74577-5e27-4fdc-a74e-67c54f382ed9",
            "sourceColumn": "Zone",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "62af329f-8009-4813-b068-450f41747be9",
        "partitions": [
          {
            "name": "Region",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\P0605227\\OneDrive - Saint-Gobain\\Desktop\\Power BI Training\\Region.xlsx\"), null, true),",
                "    Region_Sheet = Source{[Item=\"Region\",Kind=\"Sheet\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Region_Sheet,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"SAINT-GOBAIN  |  Region Master Data\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}}),",
                "    #\"Promoted Headers1\" = Table.PromoteHeaders(#\"Changed Type1\", [PromoteAllScalars=true]),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Promoted Headers1\",{{\"RegionID\", type text}, {\"RegionName\", type text}, {\"Country\", type text}, {\"Zone\", type text}})",
                "in",
                "    #\"Changed Type2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales_Historical",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SaleID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02c14d0e-c619-4b00-b26e-d84007545cab",
            "sourceColumn": "SaleID",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "01cfad7e-9feb-442a-b7ac-352e50364280",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_24f2ef6a-195b-4145-a89e-e9fdb171a737"
                },
                "isDefault": true,
                "relationship": "5f17090d-ec78-4418-b285-e78cb44379fd"
              }
            ]
          },
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4ffb09a-b653-4e12-8dc6-77b117e73059",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none"
          },
          {
            "name": "ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a11aa14e-3c60-43d1-96aa-a45a9f299a06",
            "sourceColumn": "ProductID",
            "summarizeBy": "none"
          },
          {
            "name": "RegionID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f471dc9b-d143-434a-acb4-721fff2e4920",
            "sourceColumn": "RegionID",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8cd82301-d6ed-4f10-88c4-dba2ce0674f7",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f0d7e561-8cbd-483a-8ac6-a13a120f67e9",
            "sourceColumn": "Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2450f406-784d-4c4d-a433-00d2f265e270",
            "sourceColumn": "Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "95b486b7-b573-41f6-8156-97d23f01c560",
            "sourceColumn": "Profit",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "e0abc414-df50-40f8-a252-d61ddef5f742",
        "measures": [
          {
            "name": "Total Revenue",
            "expression": "SUM(Sales_Historical[Revenue])",
            "lineageTag": "b333119a-1730-45b8-b87c-46262e853552"
          },
          {
            "name": "TotalProfit",
            "expression": "SUMX(Sales_Historical, Sales_Historical[Profit])",
            "lineageTag": "87683fec-fd9b-48ad-aa38-c705077014cd"
          },
          {
            "name": "Total Revenue Historical",
            "expression": "SUMX(Sales_Historical, Sales_Historical[Revenue])",
            "lineageTag": "c0e23cb9-8409-4d6a-8469-b405c92cabb8"
          },
          {
            "name": "Total Order Count",
            "expression": "COUNT(Sales_Historical[Quantity])",
            "lineageTag": "281183d7-3c03-4fd6-96b3-48872aeb279e"
          }
        ],
        "partitions": [
          {
            "name": "Sales_Historical",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\P0605227\\OneDrive - Saint-Gobain\\Desktop\\Power BI Training\\Sales_Historical_2022_2023.xlsx\"), null, true),",
                "    Sales_Historical_Sheet = Source{[Item=\"Sales_Historical\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sales_Historical_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"SaleID\", type text}, {\"Date\", type date}, {\"CustomerID\", type text}, {\"ProductID\", type text}, {\"RegionID\", type text}, {\"Quantity\", Int64.Type}, {\"Revenue\", type number}, {\"Cost\", type number}, {\"Profit\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_24f2ef6a-195b-4145-a89e-e9fdb171a737",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "58b9db01-427e-4a35-99e7-43324c598d10",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2ddff281-105b-49e3-84e5-e2e4cdf4dd8d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f30b38cc-057c-48d2-9da9-727bf9ae7aeb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "b4b0f1d0-b86d-4117-b6dc-b49f8c3b3482",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "49324bf9-aa06-40b9-b01f-6f8e6a37d66d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "49faf917-62c7-4ca7-849f-0421ca63acd3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9ffc7cc3-dbd0-484d-9cea-c42ca769ea1a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "12354cee-252e-46c6-9d09-3e58d6885998",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6117c278-3f95-47c5-91b0-244539877778",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "843267a1-ab60-48db-aa87-3f3160acaa44",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "6a75968e-b022-414a-8bae-a6f79a12c372",
                "ordinal": 3
              }
            ],
            "lineageTag": "a8322052-98d4-4821-8fff-abf633d65930"
          }
        ],
        "isHidden": true,
        "lineageTag": "1e81b46b-010c-421a-aeb7-70ea8571f727",
        "partitions": [
          {
            "name": "LocalDateTable_24f2ef6a-195b-4145-a89e-e9fdb171a737",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Sales_Historical'[Date])), 1, 1), Date(Year(MAX('Sales_Historical'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}